repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: integration-tests-docker
        name: Run docker-compose.test.yml + pytest
        entry: ./precommit_tests.sh
        language: system
        pass_filenames: false
        stages: [pre-push]
        files: ^(src/|tests/).*\.(py)$
