FROM postgis/postgis:16-3.4

# Copy the schema init SQL into the image so we don't rely on bind-mounts
COPY ./src/fpts/sql/ddl/phenology_metrics.sql /docker-entrypoint-initdb.d/001_phenology_metrics.sql